initial commit for treatments implementation into main chart
JohanDegraeve/xdripswift pull request #336
Opened 2022-04-01 18:38 UTC by paulplant

- stored/synced treatments will be displayed on the main chart
- carbs will be shown as a floating circle aligned with closest glucose point values
- bolus will be shown as a triangle. Micro-bolus threshold can be configured in settings (default: 1.0U). Micro-bolus will then be shown as small triangle with no labels
- option in settings to show/hide treatments on the chart (default is to show)
- changes to TreatmentType structure
- functions added to treatmentEntryAccessor
- new userdefault keys added to store new user settings
- a new chartpoint class extension has been added. This is modified from Loopkit
- correction to the NSResponse to correctly filter exercise treatments
- initial translations implemented

2022-04-04 09:01 UTC, JohanDegraeve requested changes
can you now see my review comments

2022-04-04 09:01 UTC, JohanDegraeve commented on xdrip/Constants/ConstantsGlucoseChart.swift
> +    static let glucoseCircleDiameter6h: CGFloat = 6
can you add comments to each

2022-04-04 09:01 UTC, JohanDegraeve commented on xdrip/Constants/ConstantsGlucoseChart.swift
> +    static let bolusTreatmentColor = UIColor.systemBlue
is this a color + y-axis scaling + offset?

2022-04-04 09:01 UTC, JohanDegraeve commented on xdrip/Core Data/classes/ChartPointsScatterDownTrianglesLayer.swift
> +//  ChartPointsScatterDownTrianglesLayer.swift
can you move this file to the Managers/Charts folder?

2022-04-04 09:01 UTC, JohanDegraeve commented on xdrip/Core Data/classes/TreatmentEntry+CoreDataClass.swift
> +            // if no offset is defined or  this treatment type, just return zero offset
typo : 
if no offset is defined or  this treatment type 
should be
if no offset is defined for this treatment type

2022-04-04 09:01 UTC, JohanDegraeve commented on xdrip/Extensions/ChartPoint.swift
> +    // the chartpoints defined for bolus treatment entries are abolute-positioned in the chart and need to be scaled to fit the y-axis values of the glucose chart points (and therefore avoid needing
three slashes for the declaration comments

2022-04-04 09:01 UTC, JohanDegraeve commented on xdrip/Managers/Charts/GlucoseChartManager.swift
> +    /// - smallBolus = bolus values below themicro-bolus threshold (usually around 1.0U or less)
typo : themicro

2022-04-04 09:01 UTC, JohanDegraeve commented on xdrip/Managers/Charts/GlucoseChartManager.swift
> +    private var treatmentChartPoints: TreatmentChartPointsType = ([ChartPoint](), [ChartPoint](), [ChartPoint](), [ChartPoint](), [ChartPoint](), [ChartPoint]())
can you add comments?

2022-04-04 09:01 UTC, JohanDegraeve commented on xdrip/Managers/Charts/GlucoseChartManager.swift
> +    private var smallBolusTreatmentChartPoints = [ChartPoint]()
a comment per declaration?

2022-04-04 09:01 UTC, JohanDegraeve commented on xdrip/Managers/Charts/GlucoseChartManager.swift
> +        if bgReadingsBefore.count > 0 {
better to use 

       if let lastBgReading = bgReadingsBefore.last {
            
            lowerValueToUse = lastBgReading.calculatedValue
            
        } else {
            ...
        }

2022-04-04 09:01 UTC, JohanDegraeve commented on xdrip/Managers/Charts/GlucoseChartManager.swift
> +            let bgReadingsBeforeExtended = bgReadingsAccessor.getBgReadings(from: treatmentDate.addingTimeInterval(-minutesEitherSideExtended * 60), to: treatmentDate, on: managedObjectContext)
same here : 

           if let lastBgReading = bgReadingsBeforeExtended.last {
                
                lowerValueToUse = lastBgReading.calculatedValue
                
            } else {
                ...
            }

2022-04-04 09:01 UTC, JohanDegraeve commented on xdrip/Managers/Charts/GlucoseChartManager.swift
> +            for treatmentEntry in treatmentEntries {
here you must add a filter on non-deleted treatments

treatment with treatmentdeleted equal to true, is a deleted treatment. (deleted by User). It stays in coredata with treatmentdeleted set to true, to avoid that it gets downloaded again later from NS

    for treatmentEntry in treatmentEntries.filter({ treatment in return !treatment.treatmentdeleted})

2022-04-04 09:54 UTC, paulplant commented on xdrip/Constants/ConstantsGlucoseChart.swift
> +    static let glucoseCircleDiameter6h: CGFloat = 6
Done

2022-04-04 09:54 UTC, paulplant commented on xdrip/Constants/ConstantsGlucoseChart.swift
> +    static let bolusTreatmentColor = UIColor.systemBlue
Comment corrected

2022-04-04 09:57 UTC, paulplant commented on xdrip/Core Data/classes/ChartPointsScatterDownTrianglesLayer.swift
> +//  ChartPointsScatterDownTrianglesLayer.swift
Done

2022-04-04 09:58 UTC, paulplant commented on xdrip/Core Data/classes/TreatmentEntry+CoreDataClass.swift
> +            // if no offset is defined or  this treatment type, just return zero offset
Corrected. It should have read "if no offset is defined or needed for this treatment type...."

2022-04-04 09:59 UTC, paulplant commented on xdrip/Extensions/ChartPoint.swift
> +    // the chartpoints defined for bolus treatment entries are abolute-positioned in the chart and need to be scaled to fit the y-axis values of the glucose chart points (and therefore avoid needing
Done

2022-04-04 10:26 UTC, paulplant commented on xdrip/Managers/Charts/GlucoseChartManager.swift
> +    /// - smallBolus = bolus values below themicro-bolus threshold (usually around 1.0U or less)
Done!

2022-04-04 10:27 UTC, paulplant commented on xdrip/Managers/Charts/GlucoseChartManager.swift
> +    private var treatmentChartPoints: TreatmentChartPointsType = ([ChartPoint](), [ChartPoint](), [ChartPoint](), [ChartPoint](), [ChartPoint](), [ChartPoint]())
Done

2022-04-04 10:27 UTC, paulplant commented on xdrip/Managers/Charts/GlucoseChartManager.swift
> +    private var smallBolusTreatmentChartPoints = [ChartPoint]()
Done

2022-04-04 10:34 UTC, paulplant commented on xdrip/Managers/Charts/GlucoseChartManager.swift
> +        if bgReadingsBefore.count > 0 {
Done

2022-04-04 10:34 UTC, paulplant commented on xdrip/Managers/Charts/GlucoseChartManager.swift
> +            let bgReadingsBeforeExtended = bgReadingsAccessor.getBgReadings(from: treatmentDate.addingTimeInterval(-minutesEitherSideExtended * 60), to: treatmentDate, on: managedObjectContext)
Done!

2022-04-04 10:37 UTC, paulplant commented on xdrip/Managers/Charts/GlucoseChartManager.swift
> +            for treatmentEntry in treatmentEntries {
Done

2022-04-06 08:01 UTC, paulplant commented
Decimal point issue fixed and committed @LiroyvH,  thanks!

2022-04-06 15:21 UTC, JohanDegraeve approved these changes

2022-04-07 04:47 UTC, tromanisagit commented
I got the 0 entry on the xDrip4iO5 chart, but only once, other attempts worked.  Delete works too. This was pre change, so will build again and test.  

My pref is to have some form of iob stat showing too, to track stacking of treatments.  Pref would be xDrip4iO5 calculated rather than Nightscout as offline support.

2022-04-19 19:20 UTC, LiroyvH commented
@paulplant Danke sir!
Before I forget to log it (which I kinda did for the past 2 weeks 😂😂): this problem is confirmed solved in the micro-bolus section, but still exists in the treatments window.

2022-04-25 16:52 UTC, paulplant commented
Liro

> @paulplant Danke sir!
> Before I forget to log it (which I kinda did for the past 2 weeks 😂😂): this problem is confirmed solved in the micro-bolus section, but still exists in the treatments window.

Fixed in #341 @LiroyvH , we'll get it merged into develop shortly.

This PR has actually actually been merged in by @JohanDegraeve so not sure why it's showing as Open still? I'll close it to prevent confusion.

2022-04-25 16:52 UTC, closed without merging